hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

hyperparameters:
  activation_function: 'relu'
  learning_rate: 0.001
  dropout_rate: 0.3
  optimizer: 'adam'
  batch_size: 512
  max_epochs: 2
  architecture: 'CNN_tiny'
