program: src/cifakeclassification/train.py
method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  learning-rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-1

  batch-size:
    values: [32, 64, 128, 256]

  dropout-rate:
    distribution: uniform
    min: 0.1
    max: 0.5

  architecture:
    values: ["Cifake_CNN_small", "Cifake_CNN_medium", "Cifake_Wild_large"]

  optimizer:
    values: ["adam", "sgd"]

  activation-function:
    values: ["relu", "tanh", "sigmoid", "leaky_relu"]
