command:
  - python
  - src/cifakeclassification/train.py
  - ${args_no_hyphens}
project: 02476_project1
entity: vhj-dtu
method: bayes

metric:
  name: val/loss
  goal: minimize

parameters:
  hyperparameters.learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-1

  hyperparameters.batch_size:
    values: [32, 64, 128, 256]

  hyperparameters.dropout_rate:
    distribution: uniform
    min: 0.1
    max: 0.5

  hyperparameters.architecture:
    values: ["Cifake_CNN_small", "Cifake_CNN_medium", "Cifake_Wild_large"]

  hyperparameters.optimizer:
    values: ["adam", "sgd"]

  hyperparameters.activation_function:
    values: ["relu", "tanh", "sigmoid", "leaky_relu"]

  hyperparameters.max_epochs:
    values: [5, 10, 20, 30]
