method: bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  learning_rate:
    distribution: log_uniform
    min: 0.0001
    max: 0.1
  batch_size:
    values: [32, 64, 128, 256]
  dropout_rate:
    distribution: uniform
    min: 0.1
    max: 0.5
  architecture:
    values: #tba
  optimizer:
    values: ['adam', 'sgd']
  activation_function:
    values: ['relu', 'tanh', 'sigmoid', 'leaky_relu']
  loss:
    value: 'cross_entropy'